import { Container } from "@mui/system";
import Head from "next/head";
import Layout from "../../src/components/UserDashboard/Layout/Layout";
import Dashboard from "../../src/containers/UserDashboard/Dashboard/Dashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>👩‍💻 DEV - Dashboard 👩‍💻</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container maxWidth="lg">
          <Dashboard />
        </Container>
      </Layout>
    </>
  );
}
