import { Box } from "@mui/material";
import { Container } from "@mui/system";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>👩‍💻DEV Community 👩‍💻</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg">
        <Box display={"flex"} justifyContent="space-between" ml={3.3}>
          <Link href={"/user/dashboard"}>Dashboard</Link>
        </Box>
      </Container>
    </>
  );
}
